### ISSUE TITLE
descriptionForeground colour is unreadable

### ISSUE THREAD

**Issue by StaySleeping** [selfrefactor/niketa-theme#5] opened 2022-12-05 23:27 UTC
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/6896976/205765130-30ca1023-514e-4ebc-8507-194347acd064.png">
Would be great if you could pick a different colour for descriptionForeground, its a little too bright to read.

I've also had to change the terminal cursor to be more viewable.

For anyone having this issue but loving this theme you can edit it as so:
```
"workbench.colorCustomizations": {
      "[KozmicBlues]": {
         "terminalCursor.foreground": "#000",
         "descriptionForeground": "#528ff0"
      }
   }
```

**Comment by selfrefactor** [comment] 2023-01-11 12:33
I didn't see the issue as I for some reason stop watching the repo. Thank you for filling this problem. I will make a release right away.

**Comment by selfrefactor** [comment] 2023-01-11 12:37
Released with latest version, so I will close the issue. Still, if possible, can you confirm that the issue is gone? Also, can you share a screen so I know where these colors play part?

**Closed as completed by selfrefactor** 2023-01-11 12:37 UTC
